### ISSUE TITLE
Input missing 

### ISSUE THREAD

**Issue by lauaall** [cyclone-github/base64_2_pbkdf2sha1#1]

**Comment by cyclone-github** [comment]
Looks like you are trying to use "go run" while also running the compiled binary. You can do either, but not both.
If you want to compile and run from source code, try:
`go run base64_2_pbkdf2sha1.go -i base64.txt`
Or run the compiled binary:
`./base64_2_pbkdf2sha1.bin -i base64.txt`

**Comment by lauaall** [comment]
thanks!

**Comment by lauaall** [comment]
Also the hash isn't printed to the console after running this, maybe a vscode problem, i dont know.
`go run base64_2_pbkdf2sha1.go -i base64.txt`
